// react/next imports
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// third party imports
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";

// local imports
import Header from "./_components/header/Header";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Starbucks Blog ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ToastContainer transition={Slide} />
        {children}
      </body>
    </html>
  );
}
